### ISSUE TITLE
为什么没有效果

### ISSUE THREAD

**Issue by disappear0816** [muhanstudio/docs-all-in-one#1]
不是很懂这个怎么使用, 也没有什么说明

**Comment by disappear0816** [comment]
希望能够更新操作使用说明文档

**Comment by disappear0816** [comment]
看起来蛮实用的挂件, 期待更新

**Comment by muhanstudio** [comment]
https://github.com/muhanstudio/docs-all-in-one/assets/29907393/2f5afba4-7c65-4696-963c-16ac7b599a60
如图，和其他思源笔记挂件的使用方法是一样的
